/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.lang.reflect.*;
import java.util.HashMap;
import java.util.Timer;
import javax.swing.JLabel;

/**
 * this class is to create the view the game board
 */
public class GameBoardView extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form GameBoardView
     */
    public GameBoardView() {
        initComponents();
        this.getContentPane().setBackground( Color.WHITE );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameBoardPanel = new javax.swing.JPanel();
        n2p2z0 = new javax.swing.JLabel();
        n4p4z0 = new javax.swing.JLabel();
        n3p3z0 = new javax.swing.JLabel();
        p3n3z0 = new javax.swing.JLabel();
        p4n4z0 = new javax.swing.JLabel();
        n1p1z0 = new javax.swing.JLabel();
        z0z0z0 = new javax.swing.JLabel();
        p1n1z0 = new javax.swing.JLabel();
        p2n2z0 = new javax.swing.JLabel();
        z0p4n4 = new javax.swing.JLabel();
        n4p3p1 = new javax.swing.JLabel();
        n3p2p1 = new javax.swing.JLabel();
        n2p1p1 = new javax.swing.JLabel();
        n1z0p1 = new javax.swing.JLabel();
        p1n2p1 = new javax.swing.JLabel();
        z0n1p1 = new javax.swing.JLabel();
        p2n3p1 = new javax.swing.JLabel();
        p3n4p1 = new javax.swing.JLabel();
        n4p2p2 = new javax.swing.JLabel();
        n3p1p2 = new javax.swing.JLabel();
        n2z0p2 = new javax.swing.JLabel();
        n1n1p2 = new javax.swing.JLabel();
        z0n2p2 = new javax.swing.JLabel();
        p1n3p2 = new javax.swing.JLabel();
        p2n4p2 = new javax.swing.JLabel();
        p1n4p3 = new javax.swing.JLabel();
        z0n3p3 = new javax.swing.JLabel();
        n1n2p3 = new javax.swing.JLabel();
        n2n1p3 = new javax.swing.JLabel();
        n3z0p3 = new javax.swing.JLabel();
        n4p1p3 = new javax.swing.JLabel();
        n4z0p4 = new javax.swing.JLabel();
        n3n1p4 = new javax.swing.JLabel();
        n2n2p4 = new javax.swing.JLabel();
        n1n3p4 = new javax.swing.JLabel();
        z0n4p4 = new javax.swing.JLabel();
        n3p4n1 = new javax.swing.JLabel();
        n2p3n1 = new javax.swing.JLabel();
        n1p2n1 = new javax.swing.JLabel();
        z0p1n1 = new javax.swing.JLabel();
        p1z0n1 = new javax.swing.JLabel();
        p2n1n1 = new javax.swing.JLabel();
        p3n2n1 = new javax.swing.JLabel();
        p4n3n1 = new javax.swing.JLabel();
        p4n2n2 = new javax.swing.JLabel();
        p3n1n2 = new javax.swing.JLabel();
        p2z0n2 = new javax.swing.JLabel();
        p1p1n2 = new javax.swing.JLabel();
        z0p2n2 = new javax.swing.JLabel();
        n1p3n2 = new javax.swing.JLabel();
        n2p4n2 = new javax.swing.JLabel();
        n1p4n3 = new javax.swing.JLabel();
        z0p3n3 = new javax.swing.JLabel();
        p1p2n3 = new javax.swing.JLabel();
        p2p1n3 = new javax.swing.JLabel();
        p3z0n3 = new javax.swing.JLabel();
        p4n1n3 = new javax.swing.JLabel();
        p4z0n4 = new javax.swing.JLabel();
        p3p1n4 = new javax.swing.JLabel();
        p2p2n4 = new javax.swing.JLabel();
        p1p3n4 = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        endPlayButton = new javax.swing.JButton();
        giveUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1003, 748));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1003, 748));

        gameBoardPanel.setBackground(new java.awt.Color(255, 255, 255));
        gameBoardPanel.setMaximumSize(new java.awt.Dimension(600, 480));
        gameBoardPanel.setPreferredSize(new java.awt.Dimension(600, 480));

        n2p2z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n4p4z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n3p3z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p3n3z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p4n4z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1p1z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0z0z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1n1z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p2n2z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0p4n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n4p3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n3p2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n2p1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1z0p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1n2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0n1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p2n3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p3n4p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n4p2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n3p1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n2z0p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1n1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0n2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1n3p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p2n4p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1n4p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0n3p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1n2p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n2n1p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n3z0p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n4p1p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n4z0p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n3n1p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n2n2p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1n3p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0n4p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n3p4n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n2p3n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1p2n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0p1n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1z0n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p2n1n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p3n2n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p4n3n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p4n2n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p3n1n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p2z0n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1p1n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0p2n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1p3n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n2p4n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        n1p4n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        z0p3n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1p2n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p2p1n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p3z0n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p4n1n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p4z0n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p3p1n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p2p2n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        p1p3n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        javax.swing.GroupLayout gameBoardPanelLayout = new javax.swing.GroupLayout(gameBoardPanel);
        gameBoardPanel.setLayout(gameBoardPanelLayout);
        gameBoardPanelLayout.setHorizontalGroup(
            gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(n1p3n2))
                            .addComponent(n1p4n3))
                        .addGap(32, 32, 32)
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(p2p2n4))
                            .addComponent(p1p2n3)))
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addComponent(n3p2p1)
                        .addGap(32, 32, 32)
                        .addComponent(n1p1z0)))
                .addGap(32, 32, 32)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(p3n2n1))
                    .addComponent(p1n2p1)))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(n4p1p3)
                .addGap(98, 98, 98)
                .addComponent(n2n2p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(n3z0p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(n4p3p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(n4z0p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(p2z0n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(n2z0p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(n1n1p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(n2p3n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(p1n1z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(p2n1n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(n1p2n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(529, 529, 529)
                .addComponent(p4n4z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(n3p1p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(n1n2p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(z0n1p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(z0z0z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(p3n3z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(n3p3z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(n2n1p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(p4z0n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(p4n3n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(z0p3n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(p3p1n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(p3n1n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(n2p2z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(p1z0n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(p1p3n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(p2p1n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(p2n4p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(n4p4z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(p2n2z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(p3z0n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(n3n1p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(z0p2n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(p2n3p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(z0p4n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(p3n4p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(p4n2n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(n3p4n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(p1n3p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(p1p1n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(p1n4p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(p4n1n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(n1n3p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(z0p1n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(z0n3p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(n2p4n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(n1z0p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(n4p2p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(z0n4p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(n2p1p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(z0n2p2))
        );
        gameBoardPanelLayout.setVerticalGroup(
            gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2p2n4)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(n1p3n2))
                                    .addComponent(n1p4n3)
                                    .addComponent(p1p2n3))))
                        .addGap(36, 36, 36)
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(n3p2p1))
                            .addComponent(n1p1z0)))
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(p3n2n1)
                        .addGap(36, 36, 36)
                        .addComponent(p1n2p1)))
                .addGap(36, 36, 36)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n4p1p3)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(n2n2p4))))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(n3z0p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(n4p3p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(n4z0p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(p2z0n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(n2z0p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(n1n1p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(n2p3n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(p1n1z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(p2n1n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(n1p2n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(p4n4z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(n3p1p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(n1n2p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(z0n1p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(z0z0z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(p3n3z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(n3p3z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(n2n1p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(p4z0n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(p4n3n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(z0p3n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(p3p1n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(p3n1n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(n2p2z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(p1z0n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(p1p3n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(p2p1n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(p2n4p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(n4p4z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(p2n2z0))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(p3z0n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(n3n1p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(z0p2n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(p2n3p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(z0p4n4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(p3n4p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(p4n2n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(n3p4n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(p1n3p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(p1p1n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(p1n4p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(p4n1n3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(n1n3p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(z0p1n1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(z0n3p3))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(n2p4n2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(n1z0p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(n4p2p2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(z0n4p4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(n2p1p1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(z0n2p2))
        );

        timerLabel.setBackground(new java.awt.Color(255, 255, 255));
        timerLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 60)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(152, 180, 212));
        timerLabel.setText("10");

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Home.png"))); // NOI18N
        homeButton.setToolTipText("");
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);

        endPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/endPlay.png"))); // NOI18N
        endPlayButton.setBorderPainted(false);
        endPlayButton.setContentAreaFilled(false);
        endPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPlayButtonActionPerformed(evt);
            }
        });

        giveUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/giveUp.png"))); // NOI18N
        giveUpButton.setBorderPainted(false);
        giveUpButton.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(gameBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(endPlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(giveUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endPlayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(giveUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPlayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endPlayButtonActionPerformed

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) { 
            
    }
    
    public void setTimerNumber(int number){
        timerLabel.setText("" + number);
       
    }
    
    public void updateMist(HashMap<String, Boolean> hashMap){
        
    }
    
    public void updateRobotDestruction(int playerPosition, String RobotType){
        
    }
    
    public void updatePlayerDamaged(int playerPosition, int attackPoint){
        
    }
    
    public void updatePlayerDeath(int playerPosition){
        
    }
    
    public void updateCurrentPlayer(int playerPosition){
        
    }
    
    public void updateRobotLocation(int playerPosition, String RobotType, String destination){
        
    }
    
        
    public JLabel getHexagonLabel(String coordString) throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException{
        Class<?> gameBoardViewClass = GameBoardView.class;
        Field labelField = gameBoardViewClass.getDeclaredField(coordString);
        labelField.setAccessible(true);
        return (JLabel)labelField.get(this);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endPlayButton;
    private javax.swing.JPanel gameBoardPanel;
    private javax.swing.JButton giveUpButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel n1n1p2;
    private javax.swing.JLabel n1n2p3;
    private javax.swing.JLabel n1n3p4;
    private javax.swing.JLabel n1p1z0;
    private javax.swing.JLabel n1p2n1;
    private javax.swing.JLabel n1p3n2;
    private javax.swing.JLabel n1p4n3;
    private javax.swing.JLabel n1z0p1;
    private javax.swing.JLabel n2n1p3;
    private javax.swing.JLabel n2n2p4;
    private javax.swing.JLabel n2p1p1;
    private javax.swing.JLabel n2p2z0;
    private javax.swing.JLabel n2p3n1;
    private javax.swing.JLabel n2p4n2;
    private javax.swing.JLabel n2z0p2;
    private javax.swing.JLabel n3n1p4;
    private javax.swing.JLabel n3p1p2;
    private javax.swing.JLabel n3p2p1;
    private javax.swing.JLabel n3p3z0;
    private javax.swing.JLabel n3p4n1;
    private javax.swing.JLabel n3z0p3;
    private javax.swing.JLabel n4p1p3;
    private javax.swing.JLabel n4p2p2;
    private javax.swing.JLabel n4p3p1;
    private javax.swing.JLabel n4p4z0;
    private javax.swing.JLabel n4z0p4;
    private javax.swing.JLabel p1n1z0;
    private javax.swing.JLabel p1n2p1;
    private javax.swing.JLabel p1n3p2;
    private javax.swing.JLabel p1n4p3;
    private javax.swing.JLabel p1p1n2;
    private javax.swing.JLabel p1p2n3;
    private javax.swing.JLabel p1p3n4;
    private javax.swing.JLabel p1z0n1;
    private javax.swing.JLabel p2n1n1;
    private javax.swing.JLabel p2n2z0;
    private javax.swing.JLabel p2n3p1;
    private javax.swing.JLabel p2n4p2;
    private javax.swing.JLabel p2p1n3;
    private javax.swing.JLabel p2p2n4;
    private javax.swing.JLabel p2z0n2;
    private javax.swing.JLabel p3n1n2;
    private javax.swing.JLabel p3n2n1;
    private javax.swing.JLabel p3n3z0;
    private javax.swing.JLabel p3n4p1;
    private javax.swing.JLabel p3p1n4;
    private javax.swing.JLabel p3z0n3;
    private javax.swing.JLabel p4n1n3;
    private javax.swing.JLabel p4n2n2;
    private javax.swing.JLabel p4n3n1;
    private javax.swing.JLabel p4n4z0;
    private javax.swing.JLabel p4z0n4;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JLabel z0n1p1;
    private javax.swing.JLabel z0n2p2;
    private javax.swing.JLabel z0n3p3;
    private javax.swing.JLabel z0n4p4;
    private javax.swing.JLabel z0p1n1;
    private javax.swing.JLabel z0p2n2;
    private javax.swing.JLabel z0p3n3;
    private javax.swing.JLabel z0p4n4;
    private javax.swing.JLabel z0z0z0;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the endPlayButton
	 */
	public javax.swing.JButton getEndPlayButton() {
		return endPlayButton;
	}

	/**
	 * @param endPlayButton the endPlayButton to set
	 */
	public void setEndPlayButton(javax.swing.JButton endPlayButton) {
		this.endPlayButton = endPlayButton;
	}

	/**
	 * @return the giveUpButton
	 */
	public javax.swing.JButton getGiveUpButton() {
		return giveUpButton;
	}

	/**
	 * @param giveUpButton the giveUpButton to set
	 */
	public void setGiveUpButton(javax.swing.JButton giveUpButton) {
		this.giveUpButton = giveUpButton;
	}

	/**
	 * @return the homeButton
	 */
	public javax.swing.JButton getHomeButton() {
		return homeButton;
	}

	/**
        
        public static void main(String[] args) {
            
        }
	 * @param homeButton the homeButton to set
	 */
	public void setHomeButton(javax.swing.JButton homeButton) {
		this.homeButton = homeButton;
	}

	/**
	 * @return the timerLabel
	 */
	public javax.swing.JLabel getTimerLabel() {
		return timerLabel;
	}

	/**
	 * @param timerLabel the timerLabel to set
	 */
	public void setTimerLabel(javax.swing.JLabel timerLabel) {
		this.timerLabel = timerLabel;
	}
}
