/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author chf354
 */
public class GameBoardView extends javax.swing.JFrame {

    /**
     * Creates new form GameBoardView
     */
    public GameBoardView() {
        initComponents();
        this.getContentPane().setBackground( Color.WHITE );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameBoardPanel = new javax.swing.JPanel();
        hexagonLabel29 = new javax.swing.JLabel();
        hexagonLabel27 = new javax.swing.JLabel();
        hexagonLabel28 = new javax.swing.JLabel();
        hexagonLabel34 = new javax.swing.JLabel();
        hexagonLabel35 = new javax.swing.JLabel();
        hexagonLabel30 = new javax.swing.JLabel();
        hexagonLabel31 = new javax.swing.JLabel();
        hexagonLabel32 = new javax.swing.JLabel();
        hexagonLabel33 = new javax.swing.JLabel();
        hexagonLabel1 = new javax.swing.JLabel();
        hexagonLabel36 = new javax.swing.JLabel();
        hexagonLabel37 = new javax.swing.JLabel();
        hexagonLabel38 = new javax.swing.JLabel();
        hexagonLabel39 = new javax.swing.JLabel();
        hexagonLabel41 = new javax.swing.JLabel();
        hexagonLabel40 = new javax.swing.JLabel();
        hexagonLabel42 = new javax.swing.JLabel();
        hexagonLabel43 = new javax.swing.JLabel();
        hexagonLabel44 = new javax.swing.JLabel();
        hexagonLabel45 = new javax.swing.JLabel();
        hexagonLabel46 = new javax.swing.JLabel();
        hexagonLabel47 = new javax.swing.JLabel();
        hexagonLabel48 = new javax.swing.JLabel();
        hexagonLabel49 = new javax.swing.JLabel();
        hexagonLabel50 = new javax.swing.JLabel();
        hexagonLabel56 = new javax.swing.JLabel();
        hexagonLabel55 = new javax.swing.JLabel();
        hexagonLabel54 = new javax.swing.JLabel();
        hexagonLabel53 = new javax.swing.JLabel();
        hexagonLabel52 = new javax.swing.JLabel();
        hexagonLabel51 = new javax.swing.JLabel();
        hexagonLabel57 = new javax.swing.JLabel();
        hexagonLabel58 = new javax.swing.JLabel();
        hexagonLabel59 = new javax.swing.JLabel();
        hexagonLabel60 = new javax.swing.JLabel();
        hexagonLabel61 = new javax.swing.JLabel();
        hexagonLabel19 = new javax.swing.JLabel();
        hexagonLabel20 = new javax.swing.JLabel();
        hexagonLabel21 = new javax.swing.JLabel();
        hexagonLabel22 = new javax.swing.JLabel();
        hexagonLabel23 = new javax.swing.JLabel();
        hexagonLabel24 = new javax.swing.JLabel();
        hexagonLabel25 = new javax.swing.JLabel();
        hexagonLabel26 = new javax.swing.JLabel();
        hexagonLabel18 = new javax.swing.JLabel();
        hexagonLabel17 = new javax.swing.JLabel();
        hexagonLabel16 = new javax.swing.JLabel();
        hexagonLabel15 = new javax.swing.JLabel();
        hexagonLabe14 = new javax.swing.JLabel();
        hexagonLabel13 = new javax.swing.JLabel();
        hexagonLabel12 = new javax.swing.JLabel();
        hexagonLabel6 = new javax.swing.JLabel();
        hexagonLabel7 = new javax.swing.JLabel();
        hexagonLabel8 = new javax.swing.JLabel();
        hexagonLabel9 = new javax.swing.JLabel();
        hexagonLabel10 = new javax.swing.JLabel();
        hexagonLabel11 = new javax.swing.JLabel();
        hexagonLabel5 = new javax.swing.JLabel();
        hexagonLabel4 = new javax.swing.JLabel();
        hexagonLabel3 = new javax.swing.JLabel();
        hexagonLabel2 = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1003, 748));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1003, 748));
        setPreferredSize(new java.awt.Dimension(1003, 748));

        gameBoardPanel.setBackground(new java.awt.Color(255, 255, 255));
        gameBoardPanel.setBounds(new java.awt.Rectangle(0, 0, 600, 480));
        gameBoardPanel.setMaximumSize(new java.awt.Dimension(600, 480));
        gameBoardPanel.setPreferredSize(new java.awt.Dimension(600, 480));
        gameBoardPanel.setSize(new java.awt.Dimension(600, 480));

        hexagonLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabe14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        hexagonLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N

        javax.swing.GroupLayout gameBoardPanelLayout = new javax.swing.GroupLayout(gameBoardPanel);
        gameBoardPanel.setLayout(gameBoardPanelLayout);
        gameBoardPanelLayout.setHorizontalGroup(
            gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(hexagonLabel13))
                            .addComponent(hexagonLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(hexagonLabel3))
                            .addComponent(hexagonLabel8)))
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addComponent(hexagonLabel37)
                        .addGap(32, 32, 32)
                        .addComponent(hexagonLabel30)))
                .addGap(32, 32, 32)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(hexagonLabel25))
                    .addComponent(hexagonLabel41)))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(hexagonLabel51)
                .addGap(98, 98, 98)
                .addComponent(hexagonLabel59))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(hexagonLabel52))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(hexagonLabel36))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(hexagonLabel57))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(hexagonLabel16))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(hexagonLabel46))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(hexagonLabel47))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(hexagonLabel20))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(hexagonLabel32))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(hexagonLabel24))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(hexagonLabel21))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(529, 529, 529)
                .addComponent(hexagonLabel35))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(hexagonLabel45))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(hexagonLabel54))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(hexagonLabel40))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(hexagonLabel31))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(hexagonLabel34))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(hexagonLabel28))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(hexagonLabel53))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(hexagonLabel5))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(hexagonLabel26))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(hexagonLabel7))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(hexagonLabel4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(hexagonLabel17))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(hexagonLabel29))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(hexagonLabel23))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(hexagonLabel2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(hexagonLabel9))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(hexagonLabel50))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(hexagonLabel27))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(hexagonLabel33))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(hexagonLabel10))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(hexagonLabel58))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(hexagonLabe14))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(hexagonLabel42))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(hexagonLabel1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(hexagonLabel43))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(hexagonLabel18))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(hexagonLabel19))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(hexagonLabel49))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(hexagonLabel15))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(hexagonLabel56))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(hexagonLabel11))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(hexagonLabel60))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(hexagonLabel22))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(hexagonLabel55))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(hexagonLabel12))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(hexagonLabel39))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(hexagonLabel44))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(hexagonLabel61))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(hexagonLabel38))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(hexagonLabel48))
        );
        gameBoardPanelLayout.setVerticalGroup(
            gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hexagonLabel3)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(hexagonLabel13))
                                    .addComponent(hexagonLabel6)
                                    .addComponent(hexagonLabel8))))
                        .addGap(36, 36, 36)
                        .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(hexagonLabel37))
                            .addComponent(hexagonLabel30)))
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(hexagonLabel25)
                        .addGap(36, 36, 36)
                        .addComponent(hexagonLabel41)))
                .addGap(36, 36, 36)
                .addGroup(gameBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hexagonLabel51)
                    .addGroup(gameBoardPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(hexagonLabel59))))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(hexagonLabel52))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(hexagonLabel36))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(hexagonLabel57))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(hexagonLabel16))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(hexagonLabel46))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(hexagonLabel47))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(hexagonLabel20))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel32))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(hexagonLabel24))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(hexagonLabel21))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel35))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(hexagonLabel45))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(hexagonLabel54))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(hexagonLabel40))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel31))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel34))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel28))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(hexagonLabel53))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(hexagonLabel5))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(hexagonLabel26))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(hexagonLabel7))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(hexagonLabel4))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(hexagonLabel17))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel29))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(hexagonLabel23))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(hexagonLabel2))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(hexagonLabel9))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(hexagonLabel50))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel27))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(hexagonLabel33))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(hexagonLabel10))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(hexagonLabel58))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(hexagonLabe14))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(hexagonLabel42))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(hexagonLabel1))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(hexagonLabel43))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(hexagonLabel18))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(hexagonLabel19))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(hexagonLabel49))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(hexagonLabel15))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(hexagonLabel56))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(hexagonLabel11))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(hexagonLabel60))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(hexagonLabel22))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(hexagonLabel55))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(hexagonLabel12))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(hexagonLabel39))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(hexagonLabel44))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(hexagonLabel61))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(hexagonLabel38))
            .addGroup(gameBoardPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(hexagonLabel48))
        );

        timerLabel.setBackground(new java.awt.Color(255, 255, 255));
        timerLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 60)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(152, 180, 212));
        timerLabel.setText("10");
        timerLabel.setIgnoreRepaint(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(gameBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameBoardPanel;
    private javax.swing.JLabel hexagonLabe14;
    private javax.swing.JLabel hexagonLabel1;
    private javax.swing.JLabel hexagonLabel10;
    private javax.swing.JLabel hexagonLabel11;
    private javax.swing.JLabel hexagonLabel12;
    private javax.swing.JLabel hexagonLabel13;
    private javax.swing.JLabel hexagonLabel15;
    private javax.swing.JLabel hexagonLabel16;
    private javax.swing.JLabel hexagonLabel17;
    private javax.swing.JLabel hexagonLabel18;
    private javax.swing.JLabel hexagonLabel19;
    private javax.swing.JLabel hexagonLabel2;
    private javax.swing.JLabel hexagonLabel20;
    private javax.swing.JLabel hexagonLabel21;
    private javax.swing.JLabel hexagonLabel22;
    private javax.swing.JLabel hexagonLabel23;
    private javax.swing.JLabel hexagonLabel24;
    private javax.swing.JLabel hexagonLabel25;
    private javax.swing.JLabel hexagonLabel26;
    private javax.swing.JLabel hexagonLabel27;
    private javax.swing.JLabel hexagonLabel28;
    private javax.swing.JLabel hexagonLabel29;
    private javax.swing.JLabel hexagonLabel3;
    private javax.swing.JLabel hexagonLabel30;
    private javax.swing.JLabel hexagonLabel31;
    private javax.swing.JLabel hexagonLabel32;
    private javax.swing.JLabel hexagonLabel33;
    private javax.swing.JLabel hexagonLabel34;
    private javax.swing.JLabel hexagonLabel35;
    private javax.swing.JLabel hexagonLabel36;
    private javax.swing.JLabel hexagonLabel37;
    private javax.swing.JLabel hexagonLabel38;
    private javax.swing.JLabel hexagonLabel39;
    private javax.swing.JLabel hexagonLabel4;
    private javax.swing.JLabel hexagonLabel40;
    private javax.swing.JLabel hexagonLabel41;
    private javax.swing.JLabel hexagonLabel42;
    private javax.swing.JLabel hexagonLabel43;
    private javax.swing.JLabel hexagonLabel44;
    private javax.swing.JLabel hexagonLabel45;
    private javax.swing.JLabel hexagonLabel46;
    private javax.swing.JLabel hexagonLabel47;
    private javax.swing.JLabel hexagonLabel48;
    private javax.swing.JLabel hexagonLabel49;
    private javax.swing.JLabel hexagonLabel5;
    private javax.swing.JLabel hexagonLabel50;
    private javax.swing.JLabel hexagonLabel51;
    private javax.swing.JLabel hexagonLabel52;
    private javax.swing.JLabel hexagonLabel53;
    private javax.swing.JLabel hexagonLabel54;
    private javax.swing.JLabel hexagonLabel55;
    private javax.swing.JLabel hexagonLabel56;
    private javax.swing.JLabel hexagonLabel57;
    private javax.swing.JLabel hexagonLabel58;
    private javax.swing.JLabel hexagonLabel59;
    private javax.swing.JLabel hexagonLabel6;
    private javax.swing.JLabel hexagonLabel60;
    private javax.swing.JLabel hexagonLabel61;
    private javax.swing.JLabel hexagonLabel7;
    private javax.swing.JLabel hexagonLabel8;
    private javax.swing.JLabel hexagonLabel9;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
