/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.IOException;
import java.lang.reflect.*;
import java.util.Dictionary;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.geometry.Bounds;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * this class is to create the view the game board
 */
public class GameBoardView5 extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private Timer currentRobotBlinkTimer = new Timer();
    private Class<?> gameBoardViewClass = GameBoardView5.class;
    
    private Timer animationTimer = new Timer();
    private RobotLabel currentRobotLabel = null;
    private Rectangle originalBounds = null;
    private Rectangle expectedBounds = null;
    private int animationSplitX = 0;
    private int animationSplitY = 0;

    private int previousPlayerPosition = -1;
    private int currentPlayerPosition = 0;
    private String currentRobotType = "Scout";
    
    private HashMap<RobotLabel, String> robotPositionHashMap = new HashMap<RobotLabel, String>();

    private RobotLabel player0_scout;
    private RobotLabel player0_sniper;
    private RobotLabel player0_tank;

    private RobotLabel player1_scout;
    private RobotLabel player1_sniper;
    private RobotLabel player1_tank;

    private RobotLabel player2_scout;
    private RobotLabel player2_sniper;
    private RobotLabel player2_tank;

    private RobotLabel player3_scout;
    private RobotLabel player3_sniper;
    private RobotLabel player3_tank;

    private RobotLabel player4_scout;
    private RobotLabel player4_sniper;
    private RobotLabel player4_tank;

    private RobotLabel player5_scout;
    private RobotLabel player5_sniper;
    private RobotLabel player5_tank;

    /**
     * Creates new form GameBoardView
     */
    public GameBoardView5() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameBoardPanel = new javax.swing.JPanel();
        n2p2z0 = new javax.swing.JLabel();
        n4p4z0 = new javax.swing.JLabel();
        n3p3z0 = new javax.swing.JLabel();
        p3n3z0 = new javax.swing.JLabel();
        p4n4z0 = new javax.swing.JLabel();
        n1p1z0 = new javax.swing.JLabel();
        z0z0z0 = new javax.swing.JLabel();
        p1n1z0 = new javax.swing.JLabel();
        p2n2z0 = new javax.swing.JLabel();
        z0p4n4 = new javax.swing.JLabel();
        n4p3p1 = new javax.swing.JLabel();
        n3p2p1 = new javax.swing.JLabel();
        n2p1p1 = new javax.swing.JLabel();
        n1z0p1 = new javax.swing.JLabel();
        p1n2p1 = new javax.swing.JLabel();
        z0n1p1 = new javax.swing.JLabel();
        p2n3p1 = new javax.swing.JLabel();
        p3n4p1 = new javax.swing.JLabel();
        n4p2p2 = new javax.swing.JLabel();
        n3p1p2 = new javax.swing.JLabel();
        n2z0p2 = new javax.swing.JLabel();
        n1n1p2 = new javax.swing.JLabel();
        z0n2p2 = new javax.swing.JLabel();
        p1n3p2 = new javax.swing.JLabel();
        p2n4p2 = new javax.swing.JLabel();
        p1n4p3 = new javax.swing.JLabel();
        z0n3p3 = new javax.swing.JLabel();
        n1n2p3 = new javax.swing.JLabel();
        n2n1p3 = new javax.swing.JLabel();
        n3z0p3 = new javax.swing.JLabel();
        n4p1p3 = new javax.swing.JLabel();
        n4z0p4 = new javax.swing.JLabel();
        n3n1p4 = new javax.swing.JLabel();
        n2n2p4 = new javax.swing.JLabel();
        n1n3p4 = new javax.swing.JLabel();
        z0n4p4 = new javax.swing.JLabel();
        n3p4n1 = new javax.swing.JLabel();
        n2p3n1 = new javax.swing.JLabel();
        n1p2n1 = new javax.swing.JLabel();
        z0p1n1 = new javax.swing.JLabel();
        p1z0n1 = new javax.swing.JLabel();
        p2n1n1 = new javax.swing.JLabel();
        p3n2n1 = new javax.swing.JLabel();
        p4n3n1 = new javax.swing.JLabel();
        p4n2n2 = new javax.swing.JLabel();
        p3n1n2 = new javax.swing.JLabel();
        p2z0n2 = new javax.swing.JLabel();
        p1p1n2 = new javax.swing.JLabel();
        z0p2n2 = new javax.swing.JLabel();
        n1p3n2 = new javax.swing.JLabel();
        n2p4n2 = new javax.swing.JLabel();
        n1p4n3 = new javax.swing.JLabel();
        z0p3n3 = new javax.swing.JLabel();
        p1p2n3 = new javax.swing.JLabel();
        p2p1n3 = new javax.swing.JLabel();
        p3z0n3 = new javax.swing.JLabel();
        p4n1n3 = new javax.swing.JLabel();
        p4z0n4 = new javax.swing.JLabel();
        p3p1n4 = new javax.swing.JLabel();
        p2p2n4 = new javax.swing.JLabel();
        p1p3n4 = new javax.swing.JLabel();
        yellowTeam = new javax.swing.JLabel();
        orangeTeam = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        RobotPanel = new javax.swing.JPanel();
        scoutViolet = new javax.swing.JLabel();
        sniperViolet = new javax.swing.JLabel();
        tankViolet = new javax.swing.JLabel();
        scoutRed = new javax.swing.JLabel();
        sniperRed = new javax.swing.JLabel();
        tankRed = new javax.swing.JLabel();
        scoutOrange = new javax.swing.JLabel();
        sniperOrange = new javax.swing.JLabel();
        tankOrange = new javax.swing.JLabel();
        scoutYellow = new javax.swing.JLabel();
        sniperYellow = new javax.swing.JLabel();
        tankYellow = new javax.swing.JLabel();
        scoutGreen = new javax.swing.JLabel();
        sniperGreen = new javax.swing.JLabel();
        tankGreen = new javax.swing.JLabel();
        scoutBlue = new javax.swing.JLabel();
        sniperBlue = new javax.swing.JLabel();
        tankBlue = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        endPlayButton = new javax.swing.JButton();
        giveUpButton = new javax.swing.JButton();
        redTeam = new javax.swing.JLabel();
        greenTeam = new javax.swing.JLabel();
        blueTeam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        violetTeam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1003, 748));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1003, 748));
        setPreferredSize(new java.awt.Dimension(1003, 748));
        getContentPane().setLayout(null);

        gameBoardPanel.setBackground(new java.awt.Color(255, 255, 255));
        gameBoardPanel.setMaximumSize(new java.awt.Dimension(600, 480));
        gameBoardPanel.setPreferredSize(new java.awt.Dimension(600, 480));
        gameBoardPanel.setLayout(null);

        n2p2z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n2p2z0);
        n2p2z0.setBounds(133, 207, 67, 66);

        n4p4z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n4p4z0);
        n4p4z0.setBounds(1, 207, 67, 66);

        n3p3z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n3p3z0);
        n3p3z0.setBounds(67, 207, 67, 66);

        p3n3z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p3n3z0);
        p3n3z0.setBounds(463, 207, 67, 66);

        p4n4z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p4n4z0);
        p4n4z0.setBounds(529, 207, 67, 66);

        n1p1z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1p1z0);
        n1p1z0.setBounds(199, 207, 67, 66);

        z0z0z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0z0z0);
        z0z0z0.setBounds(265, 207, 67, 66);

        p1n1z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1n1z0);
        p1n1z0.setBounds(331, 207, 67, 66);

        p2n2z0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p2n2z0);
        p2n2z0.setBounds(397, 207, 67, 66);

        z0p4n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0p4n4);
        z0p4n4.setBounds(133, 3, 67, 66);

        n4p3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n4p3p1);
        n4p3p1.setBounds(34, 258, 67, 66);

        n3p2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n3p2p1);
        n3p2p1.setBounds(100, 258, 67, 66);

        n2p1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n2p1p1);
        n2p1p1.setBounds(166, 258, 67, 66);

        n1z0p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1z0p1);
        n1z0p1.setBounds(232, 258, 67, 66);

        p1n2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1n2p1);
        p1n2p1.setBounds(364, 258, 67, 66);

        z0n1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0n1p1);
        z0n1p1.setBounds(298, 258, 67, 66);

        p2n3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p2n3p1);
        p2n3p1.setBounds(430, 258, 67, 66);

        p3n4p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p3n4p1);
        p3n4p1.setBounds(496, 258, 67, 66);

        n4p2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n4p2p2);
        n4p2p2.setBounds(67, 309, 67, 66);

        n3p1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n3p1p2);
        n3p1p2.setBounds(133, 309, 67, 66);

        n2z0p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n2z0p2);
        n2z0p2.setBounds(199, 309, 67, 66);

        n1n1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1n1p2);
        n1n1p2.setBounds(265, 309, 67, 66);

        z0n2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0n2p2);
        z0n2p2.setBounds(331, 309, 67, 66);

        p1n3p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1n3p2);
        p1n3p2.setBounds(397, 309, 67, 66);

        p2n4p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p2n4p2);
        p2n4p2.setBounds(463, 309, 67, 66);

        p1n4p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1n4p3);
        p1n4p3.setBounds(430, 360, 67, 66);

        z0n3p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0n3p3);
        z0n3p3.setBounds(364, 360, 67, 66);

        n1n2p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1n2p3);
        n1n2p3.setBounds(298, 360, 67, 66);

        n2n1p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n2n1p3);
        n2n1p3.setBounds(232, 360, 67, 66);

        n3z0p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n3z0p3);
        n3z0p3.setBounds(166, 360, 67, 66);

        n4p1p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n4p1p3);
        n4p1p3.setBounds(100, 360, 67, 66);

        n4z0p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n4z0p4);
        n4z0p4.setBounds(133, 411, 67, 66);

        n3n1p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n3n1p4);
        n3n1p4.setBounds(199, 411, 67, 66);

        n2n2p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n2n2p4);
        n2n2p4.setBounds(265, 411, 67, 66);

        n1n3p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1n3p4);
        n1n3p4.setBounds(331, 411, 67, 66);

        z0n4p4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0n4p4);
        z0n4p4.setBounds(397, 411, 67, 66);

        n3p4n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n3p4n1);
        n3p4n1.setBounds(34, 156, 67, 66);

        n2p3n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n2p3n1);
        n2p3n1.setBounds(100, 156, 67, 66);

        n1p2n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1p2n1);
        n1p2n1.setBounds(166, 156, 67, 66);

        z0p1n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0p1n1);
        z0p1n1.setBounds(232, 156, 67, 66);

        p1z0n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1z0n1);
        p1z0n1.setBounds(298, 156, 67, 66);

        p2n1n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p2n1n1);
        p2n1n1.setBounds(364, 156, 67, 66);

        p3n2n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p3n2n1);
        p3n2n1.setBounds(430, 156, 67, 66);

        p4n3n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p4n3n1);
        p4n3n1.setBounds(496, 156, 67, 66);

        p4n2n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p4n2n2);
        p4n2n2.setBounds(463, 105, 67, 66);

        p3n1n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p3n1n2);
        p3n1n2.setBounds(397, 105, 67, 66);

        p2z0n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p2z0n2);
        p2z0n2.setBounds(331, 105, 67, 66);

        p1p1n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1p1n2);
        p1p1n2.setBounds(265, 105, 67, 66);

        z0p2n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0p2n2);
        z0p2n2.setBounds(199, 105, 67, 66);

        n1p3n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1p3n2);
        n1p3n2.setBounds(133, 105, 67, 66);

        n2p4n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n2p4n2);
        n2p4n2.setBounds(67, 105, 67, 66);

        n1p4n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(n1p4n3);
        n1p4n3.setBounds(100, 54, 67, 66);

        z0p3n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(z0p3n3);
        z0p3n3.setBounds(166, 54, 67, 66);

        p1p2n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1p2n3);
        p1p2n3.setBounds(232, 54, 67, 66);

        p2p1n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p2p1n3);
        p2p1n3.setBounds(298, 54, 67, 66);

        p3z0n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p3z0n3);
        p3z0n3.setBounds(364, 54, 67, 66);

        p4n1n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p4n1n3);
        p4n1n3.setBounds(430, 54, 67, 66);

        p4z0n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p4z0n4);
        p4z0n4.setBounds(397, 3, 67, 66);

        p3p1n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p3p1n4);
        p3p1n4.setBounds(331, 3, 67, 66);

        p2p2n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p2p2n4);
        p2p2n4.setBounds(265, 3, 67, 66);

        p1p3n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Polygon.png"))); // NOI18N
        gameBoardPanel.add(p1p3n4);
        p1p3n4.setBounds(199, 3, 67, 66);

        yellowTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/yellowTeam.png"))); // NOI18N
        gameBoardPanel.add(yellowTeam);
        yellowTeam.setBounds(470, 0, 60, 30);

        orangeTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/orangeTeam.png"))); // NOI18N
        gameBoardPanel.add(orangeTeam);
        orangeTeam.setBounds(70, 0, 60, 30);

        getContentPane().add(gameBoardPanel);
        gameBoardPanel.setBounds(150, 100, 600, 480);

        timerLabel.setBackground(new java.awt.Color(255, 255, 255));
        timerLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 60)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(152, 180, 212));
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerLabel.setText("10");
        getContentPane().add(timerLabel);
        timerLabel.setBounds(410, 20, 76, 66);

        RobotPanel.setBackground(new java.awt.Color(255, 255, 255));
        RobotPanel.setMaximumSize(new java.awt.Dimension(143, 230));
        RobotPanel.setMinimumSize(new java.awt.Dimension(143, 230));
        RobotPanel.setPreferredSize(new java.awt.Dimension(143, 230));
        RobotPanel.setLayout(null);

        scoutViolet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ScoutL.png"))); // NOI18N
        scoutViolet.setBounds(new java.awt.Rectangle(0, 208, 32, 32));
        scoutViolet.setMaximumSize(new java.awt.Dimension(31, 30));
        scoutViolet.setMinimumSize(new java.awt.Dimension(31, 30));
        RobotPanel.add(scoutViolet);
        scoutViolet.setBounds(0, 208, 32, 32);

        sniperViolet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SniperL.png"))); // NOI18N
        sniperViolet.setBounds(new java.awt.Rectangle(49, 208, 38, 30));
        RobotPanel.add(sniperViolet);
        sniperViolet.setBounds(49, 208, 38, 30);

        tankViolet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TankL.png"))); // NOI18N
        tankViolet.setBounds(new java.awt.Rectangle(105, 208, 39, 32));
        RobotPanel.add(tankViolet);
        tankViolet.setBounds(105, 208, 39, 32);

        scoutRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ScoutR.png"))); // NOI18N
        scoutRed.setBounds(new java.awt.Rectangle(0, 0, 31, 30));
        RobotPanel.add(scoutRed);
        scoutRed.setBounds(0, 0, 31, 30);

        sniperRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SniperR.png"))); // NOI18N
        sniperRed.setBounds(new java.awt.Rectangle(49, 0, 38, 30));
        RobotPanel.add(sniperRed);
        sniperRed.setBounds(49, 0, 38, 30);

        tankRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TankR.png"))); // NOI18N
        tankRed.setBounds(new java.awt.Rectangle(105, 0, 38, 30));
        RobotPanel.add(tankRed);
        tankRed.setBounds(105, 0, 38, 30);

        scoutOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ScoutO.png"))); // NOI18N
        scoutOrange.setBounds(new java.awt.Rectangle(0, 42, 31, 30));
        scoutOrange.setMaximumSize(new java.awt.Dimension(31, 30));
        scoutOrange.setMinimumSize(new java.awt.Dimension(31, 30));
        RobotPanel.add(scoutOrange);
        scoutOrange.setBounds(0, 42, 32, 32);

        sniperOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SniperO.png"))); // NOI18N
        sniperOrange.setBounds(new java.awt.Rectangle(49, 42, 38, 30));
        sniperOrange.setMaximumSize(new java.awt.Dimension(38, 30));
        sniperOrange.setMinimumSize(new java.awt.Dimension(38, 30));
        RobotPanel.add(sniperOrange);
        sniperOrange.setBounds(49, 42, 39, 30);

        tankOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TankO.png"))); // NOI18N
        tankOrange.setBounds(new java.awt.Rectangle(105, 42, 38, 30));
        RobotPanel.add(tankOrange);
        tankOrange.setBounds(105, 42, 39, 30);

        scoutYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ScoutY.png"))); // NOI18N
        scoutYellow.setBounds(new java.awt.Rectangle(0, 84, 31, 30));
        RobotPanel.add(scoutYellow);
        scoutYellow.setBounds(0, 84, 31, 30);

        sniperYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SniperY.png"))); // NOI18N
        sniperYellow.setBounds(new java.awt.Rectangle(49, 84, 38, 30));
        RobotPanel.add(sniperYellow);
        sniperYellow.setBounds(49, 84, 38, 30);

        tankYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TankY.png"))); // NOI18N
        tankYellow.setBounds(new java.awt.Rectangle(105, 84, 38, 30));
        RobotPanel.add(tankYellow);
        tankYellow.setBounds(105, 84, 38, 30);

        scoutGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ScoutG.png"))); // NOI18N
        scoutGreen.setBounds(new java.awt.Rectangle(0, 126, 32, 30));
        scoutGreen.setMaximumSize(new java.awt.Dimension(31, 30));
        scoutGreen.setMinimumSize(new java.awt.Dimension(31, 30));
        RobotPanel.add(scoutGreen);
        scoutGreen.setBounds(0, 126, 32, 30);

        sniperGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SniperG.png"))); // NOI18N
        sniperGreen.setBounds(new java.awt.Rectangle(49, 126, 39, 30));
        sniperGreen.setMaximumSize(new java.awt.Dimension(38, 30));
        sniperGreen.setMinimumSize(new java.awt.Dimension(38, 30));
        RobotPanel.add(sniperGreen);
        sniperGreen.setBounds(49, 126, 39, 30);

        tankGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TankG.png"))); // NOI18N
        tankGreen.setBounds(new java.awt.Rectangle(105, 126, 39, 30));
        RobotPanel.add(tankGreen);
        tankGreen.setBounds(105, 126, 39, 30);

        scoutBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ScoutB.png"))); // NOI18N
        scoutBlue.setBounds(new java.awt.Rectangle(0, 168, 32, 30));
        scoutBlue.setMaximumSize(new java.awt.Dimension(31, 30));
        scoutBlue.setMinimumSize(new java.awt.Dimension(31, 30));
        RobotPanel.add(scoutBlue);
        scoutBlue.setBounds(0, 168, 32, 30);

        sniperBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/SniperB.png"))); // NOI18N
        sniperBlue.setBounds(new java.awt.Rectangle(49, 168, 39, 30));
        sniperBlue.setMaximumSize(new java.awt.Dimension(38, 30));
        sniperBlue.setMinimumSize(new java.awt.Dimension(38, 30));
        RobotPanel.add(sniperBlue);
        sniperBlue.setBounds(49, 168, 39, 30);

        tankBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TankB.png"))); // NOI18N
        tankBlue.setBounds(new java.awt.Rectangle(105, 168, 39, 30));
        RobotPanel.add(tankBlue);
        tankBlue.setBounds(105, 168, 39, 30);

        getContentPane().add(RobotPanel);
        RobotPanel.setBounds(810, 30, 150, 240);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Home.png"))); // NOI18N
        homeButton.setToolTipText("");
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        getContentPane().add(homeButton);
        homeButton.setBounds(29, 21, 60, 47);

        endPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/endPlay.png"))); // NOI18N
        endPlayButton.setBorderPainted(false);
        endPlayButton.setContentAreaFilled(false);
        endPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPlayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(endPlayButton);
        endPlayButton.setBounds(320, 630, 55, 66);

        giveUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/giveUp.png"))); // NOI18N
        giveUpButton.setBorderPainted(false);
        giveUpButton.setContentAreaFilled(false);
        getContentPane().add(giveUpButton);
        giveUpButton.setBounds(520, 630, 55, 63);

        redTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/redTeam.png"))); // NOI18N
        redTeam.setBounds(new java.awt.Rectangle(90, 324, 60, 30));
        getContentPane().add(redTeam);
        redTeam.setBounds(90, 324, 60, 30);

        greenTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/greenTeam.png"))); // NOI18N
        greenTeam.setBounds(new java.awt.Rectangle(750, 324, 60, 30));
        getContentPane().add(greenTeam);
        greenTeam.setBounds(750, 324, 60, 30);

        blueTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/blueTeam.png"))); // NOI18N
        getContentPane().add(blueTeam);
        blueTeam.setBounds(600, 580, 60, 30);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(95, 350, 50, 20);

        violetTeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/violetTeam.png"))); // NOI18N
        getContentPane().add(violetTeam);
        violetTeam.setBounds(240, 580, 60, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPlayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endPlayButtonActionPerformed

    public void updateTimerNumber(int number) {
        timerLabel.setText("" + number);

    }

    public void updateMist(HashMap<String, Boolean> hashMap) {
        hashMap.forEach((coordString, isVisible) -> {
            getHexagonLabel(coordString).setEnabled(isVisible);
            robotPositionHashMap.forEach((r, c)->{
                if(c.equals(coordString)){
                    r.setVisible(isVisible);
                }
            });
        });
    }

    public void updateOperationState(String state) {
        jLabel1.setText(state);
    }

    public void updateRobotDestruction(int playerPosition, String RobotType) {
        JLabel robotLabel = getRobotLabel(playerPosition, RobotType.toLowerCase());
        if (robotLabel != null) {
            gameBoardPanel.remove(robotLabel);
            gameBoardPanel.repaint();
        }
    }

    public void updateCurrentRobot(String robotType) {
        // stop the previous timer
        if(previousPlayerPosition != -1){
            currentRobotBlinkTimer.cancel();
            getRobotLabel(previousPlayerPosition, currentRobotType.toLowerCase()).setEnabled(true);
        }

        // start a new task
        currentRobotType = robotType;
        currentRobotBlinkTimer = new Timer();
        currentRobotBlinkTimer.schedule(
                new TimerTask() {
            @Override
            public void run() {
                JLabel robotLabel = getRobotLabel(currentPlayerPosition, currentRobotType.toLowerCase());
                robotLabel.setEnabled(!robotLabel.isEnabled());
            }
        },
                0,
                200
        );
    }

    public void updateRobotDamaged(int playerPosition, String robotType, int attackPoint) {

    }

    public void updatePlayerDeath(int playerPosition) {

    }
    
    public void updateRobotTurned(int playerPosition, String robotType, int direction){
        ((RobotLabel)getRobotLabel(playerPosition, robotType)).updateRotation(direction);
    }

    public void updateCurrentPlayer(int playerPosition) {
        previousPlayerPosition = currentPlayerPosition;
        currentPlayerPosition = playerPosition;
    }

    public void updateRobotLocation(int playerPosition, String RobotType, String coordString) {
        RobotLabel robotLabel = getRobotLabel(playerPosition, RobotType.toLowerCase());
        JLabel hexagonLabel = getHexagonLabel(coordString);

        animationTimer.cancel();
        
        if (hexagonLabel != null) {
            if (robotLabel == null) {
                setRobotLabel(playerPosition, RobotType, new RobotLabel(playerPosition, RobotType));
                robotLabel = getRobotLabel(playerPosition, RobotType.toLowerCase());
                robotPositionHashMap.put(getRobotLabel(playerPosition, RobotType), coordString);
                gameBoardPanel.add(robotLabel);
                robotLabel.setBounds(hexagonLabel.getBounds());
            } else {
                animationTimer = new Timer();
                currentRobotLabel = robotLabel;
                originalBounds = robotLabel.getBounds();
                expectedBounds = hexagonLabel.getBounds();
                updateAnimationSplitXY();
                animationTimer.schedule(new TimerTask() {
                    int timeCount = 0;
                    
                    @Override
                    public void run() {
                        if(timeCount > 10){
                            currentRobotLabel.setBounds(expectedBounds);
                            animationTimer.cancel();
                        } else {
                            currentRobotLabel.setBounds(new Rectangle(
                                    currentRobotLabel.getBounds().x + animationSplitX,
                                    currentRobotLabel.getBounds().y + animationSplitY,
                                    currentRobotLabel.getBounds().width,
                                    currentRobotLabel.getBounds().height
                                )
                            );
                            timeCount++;
                        }
                    }
                }, 0, 10);
            }
            
            robotPositionHashMap.replace(getRobotLabel(playerPosition, RobotType), coordString);
        }
    }
    
    private void updateAnimationSplitXY(){
        animationSplitX = (expectedBounds.x - originalBounds.x) / 10;
        animationSplitY = (expectedBounds.y - originalBounds.y) / 10;
    }

    private RobotLabel getRobotLabel(int playerPosition, String robotType) {
        try {
            Field robotField = gameBoardViewClass.getDeclaredField("player" + playerPosition + "_" + robotType.toLowerCase());
            robotField.setAccessible(true);
            return (RobotLabel) robotField.get(this);
        } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException ex) {
            return null;
        }
    }

    private void setRobotLabel(int playerPosition, String robotType, JLabel value) {
        try {
            Field robotField = gameBoardViewClass.getDeclaredField("player" + playerPosition + "_" + robotType.toLowerCase());
            robotField.setAccessible(true);
            robotField.set(this, value);
        } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException ex) {
            // do nothing
        }
    }

    public JLabel getHexagonLabel(String coordString) {
        try {
            Field labelField = gameBoardViewClass.getDeclaredField(coordString);
            labelField.setAccessible(true);
            return (JLabel) labelField.get(this);
        } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException ex) {
            return null;
        }
    }

    
//   IN CONSTRUCTION
    public JLabel getTestTurnRobot(){
//        return this.testTurnRobot;
        return null;
    }
    
    
    
//    IN CONSTRUCTION    
    public void rotateLabel2(){
        RotateImage img = new RotateImage();
        img.init();
        img.paint(img.image.getGraphics());
        ImageIcon imgIcon = new ImageIcon(img.image);
//       this.testTurnRobot.setIcon(null);
//        this.testTurnRobot.setIcon(imgIcon);
    }
    
    
    
    
//    IN CONSTRUCTION
    public void rotateLabel(JLabel label){
        
        Image img = null;
        try {
                    img  = ImageIO.read((ClassLoader.getSystemResource(
                    "Resources/"
                    + "Scout"
                    + "Y"
                    + ".png")));
            
//            img = ImageIO.read(ClassLoader.getSystemResource(
//                    "/Resources/ScoutY.png"));

        } catch (IOException ex) {
            Logger.getLogger(GameBoardView5.class.getName()).log(Level.SEVERE, null, ex);
        }
   Graphics2D g2d = (Graphics2D) img.getGraphics();
   
        g2d.rotate(1.14);
        ImageIcon imgIcon = new ImageIcon(img);
//        label.setLocation(55, 55);
        label.setIcon(imgIcon);
//        AffineTransform trans = new AffineTransform();
//        
//        Graphics2D g2d = (Graphics2D)img;
//       AffineTransform affineTransform = new AffineTransform(); 
//       affineTransform.rotate(Math.toRadians(45), x, y); 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoardView5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoardView5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoardView5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoardView5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoardView5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RobotPanel;
    private javax.swing.JLabel blueTeam;
    private javax.swing.JButton endPlayButton;
    private javax.swing.JPanel gameBoardPanel;
    private javax.swing.JButton giveUpButton;
    private javax.swing.JLabel greenTeam;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel n1n1p2;
    private javax.swing.JLabel n1n2p3;
    private javax.swing.JLabel n1n3p4;
    private javax.swing.JLabel n1p1z0;
    private javax.swing.JLabel n1p2n1;
    private javax.swing.JLabel n1p3n2;
    private javax.swing.JLabel n1p4n3;
    private javax.swing.JLabel n1z0p1;
    private javax.swing.JLabel n2n1p3;
    private javax.swing.JLabel n2n2p4;
    private javax.swing.JLabel n2p1p1;
    private javax.swing.JLabel n2p2z0;
    private javax.swing.JLabel n2p3n1;
    private javax.swing.JLabel n2p4n2;
    private javax.swing.JLabel n2z0p2;
    private javax.swing.JLabel n3n1p4;
    private javax.swing.JLabel n3p1p2;
    private javax.swing.JLabel n3p2p1;
    private javax.swing.JLabel n3p3z0;
    private javax.swing.JLabel n3p4n1;
    private javax.swing.JLabel n3z0p3;
    private javax.swing.JLabel n4p1p3;
    private javax.swing.JLabel n4p2p2;
    private javax.swing.JLabel n4p3p1;
    private javax.swing.JLabel n4p4z0;
    private javax.swing.JLabel n4z0p4;
    private javax.swing.JLabel orangeTeam;
    private javax.swing.JLabel p1n1z0;
    private javax.swing.JLabel p1n2p1;
    private javax.swing.JLabel p1n3p2;
    private javax.swing.JLabel p1n4p3;
    private javax.swing.JLabel p1p1n2;
    private javax.swing.JLabel p1p2n3;
    private javax.swing.JLabel p1p3n4;
    private javax.swing.JLabel p1z0n1;
    private javax.swing.JLabel p2n1n1;
    private javax.swing.JLabel p2n2z0;
    private javax.swing.JLabel p2n3p1;
    private javax.swing.JLabel p2n4p2;
    private javax.swing.JLabel p2p1n3;
    private javax.swing.JLabel p2p2n4;
    private javax.swing.JLabel p2z0n2;
    private javax.swing.JLabel p3n1n2;
    private javax.swing.JLabel p3n2n1;
    private javax.swing.JLabel p3n3z0;
    private javax.swing.JLabel p3n4p1;
    private javax.swing.JLabel p3p1n4;
    private javax.swing.JLabel p3z0n3;
    private javax.swing.JLabel p4n1n3;
    private javax.swing.JLabel p4n2n2;
    private javax.swing.JLabel p4n3n1;
    private javax.swing.JLabel p4n4z0;
    private javax.swing.JLabel p4z0n4;
    private javax.swing.JLabel redTeam;
    private javax.swing.JLabel scoutBlue;
    private javax.swing.JLabel scoutGreen;
    private javax.swing.JLabel scoutOrange;
    private javax.swing.JLabel scoutRed;
    private javax.swing.JLabel scoutViolet;
    private javax.swing.JLabel scoutYellow;
    private javax.swing.JLabel sniperBlue;
    private javax.swing.JLabel sniperGreen;
    private javax.swing.JLabel sniperOrange;
    private javax.swing.JLabel sniperRed;
    private javax.swing.JLabel sniperViolet;
    private javax.swing.JLabel sniperYellow;
    private javax.swing.JLabel tankBlue;
    private javax.swing.JLabel tankGreen;
    private javax.swing.JLabel tankOrange;
    private javax.swing.JLabel tankRed;
    private javax.swing.JLabel tankViolet;
    private javax.swing.JLabel tankYellow;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JLabel violetTeam;
    private javax.swing.JLabel yellowTeam;
    private javax.swing.JLabel z0n1p1;
    private javax.swing.JLabel z0n2p2;
    private javax.swing.JLabel z0n3p3;
    private javax.swing.JLabel z0n4p4;
    private javax.swing.JLabel z0p1n1;
    private javax.swing.JLabel z0p2n2;
    private javax.swing.JLabel z0p3n3;
    private javax.swing.JLabel z0p4n4;
    private javax.swing.JLabel z0z0z0;
    // End of variables declaration//GEN-END:variables
	/**
     * @return the endPlayButton
     */
    public javax.swing.JButton getEndPlayButton() {
        return endPlayButton;
    }

    /**
     * @param endPlayButton the endPlayButton to set
     */
    public void setEndPlayButton(javax.swing.JButton endPlayButton) {
        this.endPlayButton = endPlayButton;
    }

    /**
     * @return the giveUpButton
     */
    public javax.swing.JButton getGiveUpButton() {
        return giveUpButton;
    }

    /**
     * @param giveUpButton the giveUpButton to set
     */
    public void setGiveUpButton(javax.swing.JButton giveUpButton) {
        this.giveUpButton = giveUpButton;
    }

    /**
     * @return the homeButton
     */
    public javax.swing.JButton getHomeButton() {
        return homeButton;
    }

    /**
     *
     * public static void main(String[] args) {
     *
     * }
     *
     * @param homeButton the homeButton to set
     */
    public void setHomeButton(javax.swing.JButton homeButton) {
        this.homeButton = homeButton;
    }

    /**
     * @return the timerLabel
     */
    public javax.swing.JLabel getTimerLabel() {
        return timerLabel;
    }

    /**
     * @param timerLabel the timerLabel to set
     */
    public void setTimerLabel(javax.swing.JLabel timerLabel) {
        this.timerLabel = timerLabel;
    }
}
