/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 * 
 */
public class SetGameModeView extends javax.swing.JFrame {

    /**
     * Creates new form SetGameModelView
     */
    public SetGameModeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pvpRadioButton = new javax.swing.JRadioButton();
        avaRadioButton = new javax.swing.JRadioButton();
        pvaRadioButton = new javax.swing.JRadioButton();
        twoPlayersRadioButton = new javax.swing.JRadioButton();
        threePlayersRadioButton = new javax.swing.JRadioButton();
        sixPlayersRadioButton = new javax.swing.JRadioButton();
        playerTypeComboBox1 = new javax.swing.JComboBox<String>();
        playerTypeComboBox2 = new javax.swing.JComboBox<String>();
        playerTypeComboBox3 = new javax.swing.JComboBox<String>();
        confirmButton = new javax.swing.JButton();
        playerTypeComboBox4 = new javax.swing.JComboBox();
        playerTypeComboBox5 = new javax.swing.JComboBox();
        playerTypeComboBox6 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1003, 748));
        setMaximumSize(new java.awt.Dimension(1003, 748));
        setMinimumSize(new java.awt.Dimension(1003, 748));
        setPreferredSize(new java.awt.Dimension(1003, 748));

        buttonGroup1.add(pvpRadioButton);
        pvpRadioButton.setText("Human VS Human");
        pvpRadioButton.setToolTipText("");
        pvpRadioButton.setBorderPainted(true);
        pvpRadioButton.setMargin(new java.awt.Insets(1, 1, 1, 1));

        buttonGroup1.add(avaRadioButton);
        avaRadioButton.setText("AI VS AI");
        avaRadioButton.setToolTipText("");
        avaRadioButton.setAutoscrolls(true);
        avaRadioButton.setBorderPainted(true);
        avaRadioButton.setMargin(new java.awt.Insets(1, 1, 1, 1));
        avaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(pvaRadioButton);
        pvaRadioButton.setText("Human VS AI");
        pvaRadioButton.setToolTipText("");
        pvaRadioButton.setBorderPainted(true);
        pvaRadioButton.setMargin(new java.awt.Insets(1, 1, 1, 1));
        pvaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvaRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(twoPlayersRadioButton);
        twoPlayersRadioButton.setText("Two Players");
        twoPlayersRadioButton.setBorderPainted(true);

        buttonGroup2.add(threePlayersRadioButton);
        threePlayersRadioButton.setText("Three Players");
        threePlayersRadioButton.setBorderPainted(true);
        threePlayersRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePlayersRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(sixPlayersRadioButton);
        sixPlayersRadioButton.setText("Six players");
        sixPlayersRadioButton.setBorderPainted(true);

        playerTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        playerTypeComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));
        playerTypeComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerTypeComboBox2ActionPerformed(evt);
            }
        });

        playerTypeComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        confirmButton.setText("Confirm");
        confirmButton.setToolTipText("");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        playerTypeComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        playerTypeComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        playerTypeComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerTypeComboBox6, 0, 159, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(playerTypeComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pvpRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avaRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pvaRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twoPlayersRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(threePlayersRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sixPlayersRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                .addGap(429, 429, 429))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(pvpRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pvaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(twoPlayersRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threePlayersRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sixPlayersRadioButton)
                .addGap(18, 18, 18)
                .addComponent(playerTypeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avaRadioButtonActionPerformed

    private void pvaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pvaRadioButtonActionPerformed

    private void threePlayersRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePlayersRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threePlayersRadioButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void playerTypeComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerTypeComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerTypeComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetGameModeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton avaRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> playerTypeComboBox1;
    private javax.swing.JComboBox<String> playerTypeComboBox2;
    private javax.swing.JComboBox<String> playerTypeComboBox3;
    private javax.swing.JComboBox playerTypeComboBox4;
    private javax.swing.JComboBox playerTypeComboBox5;
    private javax.swing.JComboBox playerTypeComboBox6;
    private javax.swing.JRadioButton pvaRadioButton;
    private javax.swing.JRadioButton pvpRadioButton;
    private javax.swing.JRadioButton sixPlayersRadioButton;
    private javax.swing.JRadioButton threePlayersRadioButton;
    private javax.swing.JRadioButton twoPlayersRadioButton;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the avaRadioButton
	 */
	public javax.swing.JRadioButton getAvaRadioButton() {
		return avaRadioButton;
	}

	/**
	 * @param avaRadioButton the avaRadioButton to set
	 */
	public void setAvaRadioButton(javax.swing.JRadioButton avaRadioButton) {
		this.avaRadioButton = avaRadioButton;
	}

	/**
	 * @return the buttonGroup1
	 */
	public javax.swing.ButtonGroup getButtonGroup1() {
		return buttonGroup1;
	}

	/**
	 * @param buttonGroup1 the buttonGroup1 to set
	 */
	public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
		this.buttonGroup1 = buttonGroup1;
	}

	/**
	 * @return the buttonGroup2
	 */
	public javax.swing.ButtonGroup getButtonGroup2() {
		return buttonGroup2;
	}

	/**
	 * @param buttonGroup2 the buttonGroup2 to set
	 */
	public void setButtonGroup2(javax.swing.ButtonGroup buttonGroup2) {
		this.buttonGroup2 = buttonGroup2;
	}

	/**
	 * @return the confirmButton
	 */
	public javax.swing.JButton getConfirmButton() {
		return confirmButton;
	}

	/**
	 * @param confirmButton the confirmButton to set
	 */
	public void setConfirmButton(javax.swing.JButton confirmButton) {
		this.confirmButton = confirmButton;
	}

	/**
	 * @return the playerTypeComboBox1
	 */
	public javax.swing.JComboBox<String> getPlayerTypeComboBox1() {
		return playerTypeComboBox1;
	}

	/**
	 * @param playerTypeComboBox1 the playerTypeComboBox1 to set
	 */
	public void setPlayerTypeComboBox1(javax.swing.JComboBox<String> playerTypeComboBox1) {
		this.playerTypeComboBox1 = playerTypeComboBox1;
	}

	/**
	 * @return the playerTypeComboBox2
	 */
	public javax.swing.JComboBox<String> getPlayerTypeComboBox2() {
		return playerTypeComboBox2;
	}

	/**
	 * @param playerTypeComboBox2 the playerTypeComboBox2 to set
	 */
	public void setPlayerTypeComboBox2(javax.swing.JComboBox<String> playerTypeComboBox2) {
		this.playerTypeComboBox2 = playerTypeComboBox2;
	}

	/**
	 * @return the playerTypeComboBox3
	 */
	public javax.swing.JComboBox<String> getPlayerTypeComboBox3() {
		return playerTypeComboBox3;
	}

	/**
	 * @param playerTypeComboBox3 the playerTypeComboBox3 to set
	 */
	public void setPlayerTypeComboBox3(javax.swing.JComboBox<String> playerTypeComboBox3) {
		this.playerTypeComboBox3 = playerTypeComboBox3;
	}

	/**
	 * @return the playerTypeComboBox4
	 */
	public javax.swing.JComboBox getPlayerTypeComboBox4() {
		return playerTypeComboBox4;
	}

	/**
	 * @param playerTypeComboBox4 the playerTypeComboBox4 to set
	 */
	public void setPlayerTypeComboBox4(javax.swing.JComboBox playerTypeComboBox4) {
		this.playerTypeComboBox4 = playerTypeComboBox4;
	}

	/**
	 * @return the playerTypeComboBox5
	 */
	public javax.swing.JComboBox getPlayerTypeComboBox5() {
		return playerTypeComboBox5;
	}

	/**
	 * @param playerTypeComboBox5 the playerTypeComboBox5 to set
	 */
	public void setPlayerTypeComboBox5(javax.swing.JComboBox playerTypeComboBox5) {
		this.playerTypeComboBox5 = playerTypeComboBox5;
	}

	/**
	 * @return the playerTypeComboBox6
	 */
	public javax.swing.JComboBox getPlayerTypeComboBox6() {
		return playerTypeComboBox6;
	}

	/**
	 * @param playerTypeComboBox6 the playerTypeComboBox6 to set
	 */
	public void setPlayerTypeComboBox6(javax.swing.JComboBox playerTypeComboBox6) {
		this.playerTypeComboBox6 = playerTypeComboBox6;
	}

	/**
	 * @return the pvaRadioButton
	 */
	public javax.swing.JRadioButton getPvaRadioButton() {
		return pvaRadioButton;
	}

	/**
	 * @param pvaRadioButton the pvaRadioButton to set
	 */
	public void setPvaRadioButton(javax.swing.JRadioButton pvaRadioButton) {
		this.pvaRadioButton = pvaRadioButton;
	}

	/**
	 * @return the pvpRadioButton
	 */
	public javax.swing.JRadioButton getPvpRadioButton() {
		return pvpRadioButton;
	}

	/**
	 * @param pvpRadioButton the pvpRadioButton to set
	 */
	public void setPvpRadioButton(javax.swing.JRadioButton pvpRadioButton) {
		this.pvpRadioButton = pvpRadioButton;
	}

	/**
	 * @return the sixPlayersRadioButton
	 */
	public javax.swing.JRadioButton getSixPlayersRadioButton() {
		return sixPlayersRadioButton;
	}

	/**
	 * @param sixPlayersRadioButton the sixPlayersRadioButton to set
	 */
	public void setSixPlayersRadioButton(javax.swing.JRadioButton sixPlayersRadioButton) {
		this.sixPlayersRadioButton = sixPlayersRadioButton;
	}

	/**
	 * @return the threePlayersRadioButton
	 */
	public javax.swing.JRadioButton getThreePlayersRadioButton() {
		return threePlayersRadioButton;
	}

	/**
	 * @param threePlayersRadioButton the threePlayersRadioButton to set
	 */
	public void setThreePlayersRadioButton(javax.swing.JRadioButton threePlayersRadioButton) {
		this.threePlayersRadioButton = threePlayersRadioButton;
	}

	/**
	 * @return the twoPlayersRadioButton
	 */
	public javax.swing.JRadioButton getTwoPlayersRadioButton() {
		return twoPlayersRadioButton;
	}

	/**
	 * @param twoPlayersRadioButton the twoPlayersRadioButton to set
	 */
	public void setTwoPlayersRadioButton(javax.swing.JRadioButton twoPlayersRadioButton) {
		this.twoPlayersRadioButton = twoPlayersRadioButton;
	}
	
    
}
