/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 * 
 */
public class SetGameModeView extends javax.swing.JFrame {

    /**
     * Creates new form SetGameModelView
     */
    public SetGameModeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        twoPlayersRadioButton = new javax.swing.JRadioButton();
        threePlayersRadioButton = new javax.swing.JRadioButton();
        sixPlayersRadioButton = new javax.swing.JRadioButton();
        playerTypeComboBox1 = new javax.swing.JComboBox<String>();
        playerTypeComboBox2 = new javax.swing.JComboBox<String>();
        playerTypeComboBox3 = new javax.swing.JComboBox<String>();
        confirmButton = new javax.swing.JButton();
        playerTypeComboBox4 = new javax.swing.JComboBox();
        playerTypeComboBox5 = new javax.swing.JComboBox();
        playerTypeComboBox6 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1003, 748));
        setMaximumSize(new java.awt.Dimension(1003, 748));
        setMinimumSize(new java.awt.Dimension(1003, 748));
        setPreferredSize(new java.awt.Dimension(1003, 748));

        buttonGroup2.add(twoPlayersRadioButton);
        twoPlayersRadioButton.setText("Two Players");
        twoPlayersRadioButton.setBorderPainted(true);
        twoPlayersRadioButton.setMaximumSize(new java.awt.Dimension(200, 50));
        twoPlayersRadioButton.setMinimumSize(new java.awt.Dimension(200, 50));
        twoPlayersRadioButton.setPreferredSize(new java.awt.Dimension(200, 50));
        twoPlayersRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPlayersRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(threePlayersRadioButton);
        threePlayersRadioButton.setText("Three Players");
        threePlayersRadioButton.setBorderPainted(true);
        threePlayersRadioButton.setMaximumSize(new java.awt.Dimension(200, 50));
        threePlayersRadioButton.setMinimumSize(new java.awt.Dimension(200, 50));
        threePlayersRadioButton.setPreferredSize(new java.awt.Dimension(200, 50));
        threePlayersRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePlayersRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(sixPlayersRadioButton);
        sixPlayersRadioButton.setText("Six players");
        sixPlayersRadioButton.setBorderPainted(true);
        sixPlayersRadioButton.setMaximumSize(new java.awt.Dimension(200, 50));
        sixPlayersRadioButton.setMinimumSize(new java.awt.Dimension(200, 50));
        sixPlayersRadioButton.setPreferredSize(new java.awt.Dimension(200, 50));

        playerTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        playerTypeComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));
        playerTypeComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerTypeComboBox2ActionPerformed(evt);
            }
        });

        playerTypeComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        confirmButton.setText("Confirm");
        confirmButton.setToolTipText("");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        playerTypeComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        playerTypeComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        playerTypeComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(playerTypeComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerTypeComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(twoPlayersRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(threePlayersRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sixPlayersRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(429, 429, 429))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(twoPlayersRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threePlayersRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sixPlayersRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(playerTypeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTypeComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void threePlayersRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePlayersRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threePlayersRadioButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void playerTypeComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerTypeComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerTypeComboBox2ActionPerformed

    private void twoPlayersRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPlayersRadioButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_twoPlayersRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetGameModeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetGameModeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> playerTypeComboBox1;
    private javax.swing.JComboBox<String> playerTypeComboBox2;
    private javax.swing.JComboBox<String> playerTypeComboBox3;
    private javax.swing.JComboBox playerTypeComboBox4;
    private javax.swing.JComboBox playerTypeComboBox5;
    private javax.swing.JComboBox playerTypeComboBox6;
    private javax.swing.JRadioButton sixPlayersRadioButton;
    private javax.swing.JRadioButton threePlayersRadioButton;
    private javax.swing.JRadioButton twoPlayersRadioButton;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the buttonGroup1
	 */
	public javax.swing.ButtonGroup getButtonGroup1() {
		return buttonGroup1;
	}

	/**
	 * @param buttonGroup1 the buttonGroup1 to set
	 */
	public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
		this.buttonGroup1 = buttonGroup1;
	}

	/**
	 * @return the buttonGroup2
	 */
	public javax.swing.ButtonGroup getButtonGroup2() {
		return buttonGroup2;
	}

	/**
	 * @param buttonGroup2 the buttonGroup2 to set
	 */
	public void setButtonGroup2(javax.swing.ButtonGroup buttonGroup2) {
		this.buttonGroup2 = buttonGroup2;
	}

	/**
	 * @return the jButton1
	 */
	public javax.swing.JButton getjButton1() {
		return confirmButton;
	}

	/**
	 * @param jButton1 the jButton1 to set
	 */
	public void setjButton1(javax.swing.JButton jButton1) {
		this.confirmButton = jButton1;
	}

	/**
	 * @return the jComboBox1
	 */
	public javax.swing.JComboBox<String> getjComboBox1() {
		return playerTypeComboBox1;
	}

	/**
	 * @param jComboBox1 the jComboBox1 to set
	 */
	public void setjComboBox1(javax.swing.JComboBox<String> jComboBox1) {
		this.playerTypeComboBox1 = jComboBox1;
	}

	/**
	 * @return the jComboBox2
	 */
	public javax.swing.JComboBox<String> getjComboBox2() {
		return playerTypeComboBox2;
	}

	/**
	 * @param jComboBox2 the jComboBox2 to set
	 */
	public void setjComboBox2(javax.swing.JComboBox<String> jComboBox2) {
		this.playerTypeComboBox2 = jComboBox2;
	}

	/**
	 * @return the jComboBox3
	 */
	public javax.swing.JComboBox<String> getjComboBox3() {
		return playerTypeComboBox3;
	}

	/**
	 * @param jComboBox3 the jComboBox3 to set
	 */
	public void setjComboBox3(javax.swing.JComboBox<String> jComboBox3) {
		this.playerTypeComboBox3 = jComboBox3;
	}

	/**
	 * @return the jRadioButton1
	 */
	public javax.swing.JRadioButton getjRadioButton1() {
		return pvpRadioButton;
	}

	/**
	 * @param jRadioButton1 the jRadioButton1 to set
	 */
	public void setjRadioButton1(javax.swing.JRadioButton jRadioButton1) {
		this.pvpRadioButton = jRadioButton1;
	}

	/**
	 * @return the jRadioButton2
	 */
	public javax.swing.JRadioButton getjRadioButton2() {
		return avaRadioButton;
	}

	/**
	 * @param jRadioButton2 the jRadioButton2 to set
	 */
	public void setjRadioButton2(javax.swing.JRadioButton jRadioButton2) {
		this.avaRadioButton = jRadioButton2;
	}

	/**
	 * @return the jRadioButton3
	 */
	public javax.swing.JRadioButton getjRadioButton3() {
		return pvaRadioButton;
	}

	/**
	 * @param jRadioButton3 the jRadioButton3 to set
	 */
	public void setjRadioButton3(javax.swing.JRadioButton jRadioButton3) {
		this.pvaRadioButton = jRadioButton3;
	}

	/**
	 * @return the jRadioButton4
	 */
	public javax.swing.JRadioButton getjRadioButton4() {
		return twoPlayersRadioButton;
	}

	/**
	 * @param jRadioButton4 the jRadioButton4 to set
	 */
	public void setjRadioButton4(javax.swing.JRadioButton jRadioButton4) {
		this.twoPlayersRadioButton = jRadioButton4;
	}

	/**
	 * @return the jRadioButton5
	 */
	public javax.swing.JRadioButton getjRadioButton5() {
		return threePlayersRadioButton;
	}

	/**
	 * @param jRadioButton5 the jRadioButton5 to set
	 */
	public void setjRadioButton5(javax.swing.JRadioButton jRadioButton5) {
		this.threePlayersRadioButton = jRadioButton5;
	}

	/**
	 * @return the jRadioButton6
	 */
	public javax.swing.JRadioButton getjRadioButton6() {
		return sixPlayersRadioButton;
	}

	/**
	 * @param jRadioButton6 the jRadioButton6 to set
	 */
	public void setjRadioButton6(javax.swing.JRadioButton jRadioButton6) {
		this.sixPlayersRadioButton = jRadioButton6;
	}
    
    
}
